= Goals
:experimental:
:imagesdir: images

== Workshop goals
{{ EAP8_VERSION }} adds exciting new functionality in the areas of provisioning, cloud tooling, security, and Jakarta EE 10 compliance. The move to Jakarta EE 10 introduced some changes which will require customers to update their JBoss EAP 7.x applications to enable them to run on JBoss EAP 8.0.

In this lab you will be guided through these changes, working through the migration of a typical JBoss EAP 7.0 application to JBoss EAP 8.0 on traditional environments and OpenShift. In addition to the changes introduced with Jakarta EE 10, this lab will also cover the migration from lagacy vaults to Elytron credential stores.

During the lab users will use the Migration Toolkit for Applications and the JBoss EAP Server Migration tool to help identify issues and automate code changes.

The workshop covers the following areas:

* Deployment of a sample application on JBoss EAP 7.4 
* Re-platform sample JBoss EAP 7.4 application on OpenShift
* Provision {{ EAP8_VERSION }} server and migrate the server configuration from JBoss EAP 7.4 to {{ EAP8_VERSION }}
* Perform code changes to migrate the application from EAP 7 to {{ EAP8_VERSION }}
* Migrate {{ EAP8_VERSION }} application to OpenShift
* Deploy {{ EAP8_VERSION }} application to OpenShift