= JBoss EAP Environments
:experimental:
:imagesdir: images

We've deployed two instances of JBoss EAP ready for you to deploy and migrate applications to.  These two environments consist of:

* An instance of JBoss EAP 7.4
* An instance of {{ EAP8_VERSION }}

Details of these instances are as follows.

[cols="1,1,1,1"]
|===
|Version|home directory|Front-end url|Admin console url

|JBoss EAP 7.4
|/shared/jboss-eap-7.4
|https://{{ USER_ID }}-jboss-workshop-eap7.{{ ROUTE_SUBDOMAIN }}[link, window="_blank"]
|https://{{ USER_ID }}-jboss-workshop-eap7-console.{{ ROUTE_SUBDOMAIN }}[link, window="_blank"]
|{{ EAP8_VERSION }}
|/shared/{{ JBOSS8_DIR }}
|https://{{ USER_ID }}-jboss-workshop-eap8.{{ ROUTE_SUBDOMAIN }}[link, window="_blank"]
|https://{{ USER_ID }}-jboss-workshop-eap8-console.{{ ROUTE_SUBDOMAIN }}[link, window="_blank"]
|=== 

You will be able to login to the JBoss EAP Admin consoles with the credentials:

* username: admin
* password: password

You can also access these JBoss instances using the JBoss CLI.  

For JBoss EAP 7.4 run the following from the dev spaces terminal:

[source,sh,role="copypaste"]
----
$EAP7_HOME/bin/jboss-cli.sh --connect --controller=127.0.0.1:10090
----

For {{ EAP8_VERSION }} run the following from the dev spaces terminal:

[source,sh,role="copypaste"]
----
$EAP8_HOME/bin/jboss-cli.sh --connect --controller=127.0.0.1:10190
----

Take some time to access these urls,try the jboss-cli connection, and login to the admin consoles for both instances. 
