= Traditional app deployment on JBoss 7.4
:experimental:
:imagesdir: images

JBoss EAP 8.0 will provide support for https://jakarta.ee/release/10/[Jakarta EE 10]. Jakarta EE 10 brings a huge change to Jakarta EE compared to the Jakarta EE 8 specifications supported by EAP 7. JBoss EAP 8 also introduces changes in the following areas:

* Removal of Picketbox: This has been deprecated since the release of JBoss EAP 6.4. Any legacy security configurations must be migrated to the Elytron security subsystem. EAP users who have already migrated to Elytron don't need to make any changes.
* Removal of PicketLink: This has been deprecated since the release of JBoss EAP 6.4. Leveraging RH SSO is recommended for the single sign-on functionality previously offered with PicketLink.
Support for OpenID Connect (OIDC) will now be provided by the elytron-oidc-client subsystem instead of the separate RH-SSO OIDC adapter.
* SAML support is provided by the RH-SSO SAML adapter (Picketlink SAML has been removed). In JBoss EAP 8.0 GA, support for SAML will be provided by a new RH-SSO SAML Galleon Feature Pack.
* Hibernate 6.x: Read the https://docs.jboss.org/hibernate/search/6.0/migration/html_single/[Hibernate Search article] for guidance on migrating from 5.11.x to 6.0.x.
* Removal of JDK 8: JDK 11 or JDK 17 is now required.
* Jolokia and Prometheus removed: Red Hat will no longer support these features. JBoss EAP server exposes metrics through the server metrics endpoint: <server address>:<management port>/metrics.
Apache Log4j version 1 APIs removed: If your applications do not package log4j.jar and Log4j configuration as part of the application, then you must update them.
* New maven plugin: The new eap-maven-plugin uses Galleon technology to build the server based on the layer configuration needed in your application. This results in a reduced size and memory footprint, plus a reduced attack surface. If the JAR impacted by a CVE is not present, EAP will not be vulnerable to the CVE. The JBoss EAP 8 OpenShift images don’t contain EAP runtime binaries like it used to in EAP 6 and EAP 7. This plugin also supports the execution of JBoss EAP CLI script files to customize your server configuration. OpenShift Source to Image builds (S2I) incorporate this change and have been redesigned to leverage the eap-maven-plugin to create the server. You can find more information in the https://access.redhat.com/documentation/en-us/red_hat_jboss_enterprise_application_platform/8.0-beta/[documentation].
* Bridge deploy fail: Previously, if a bridge were misconfigured, you wouldn’t know until you tried to use it. Now, the bridge will fail when added if it fails to deploy.

Refer to the https://access.redhat.com/documentation/en-us/red_hat_jboss_enterprise_application_platform/8-beta/html/release_notes_for_red_hat_jboss_enterprise_application_platform_8.0_beta/index[release notes] for more information about the changes introduced in this beta release.

Moving applications from JBoss EAP 7.4 to JBoss EAP 8.0 Beta will require code changes due to the move from Jakarta EE 8 to Jakarta EE 10 (e.g., converting from the “javax” namespace to “jakarta” namespace). These changes are documented in this https://access.redhat.com/articles/6980265[article]. To help our customers with this migration effort we've updated our tools: the https://developers.redhat.com/products/mta/download[Migration Toolkit for Applications], including the Migration Toolkit for Runtimes (MTR, for non-OpenShift projects) and the JBoss EAP Server Migration tool. 

In this section we're going to use the JBoss EAP Server Migration tool migrate the server configuration from JBoss EAP 7.4 to JBoss EAP 8-Beta

We now have a running instance of our application running in JBoss EAP 7.4 ready to migrate to JBoss EAP 8.0 Beta. Before starting the migration, shut down the JBoss EAP 7.4 server and create an environment variable pointing to the JBoss EAP 7.4 deployment.

[source,sh,role="copypaste"]
----
export EAP_PREVIOUS_HOME=/shared/jboss-eap-7.4
----


You will find a JBoss EAP 8-Beta archive in the "/shared" folder.  From the terminal enter the following commands:

[source,sh,role="copypaste"]
----
cd /shared
----

[source,sh,role="copypaste"]
----
unzip jboss-eap-8.0.0.Beta.zip 
----

Extract the distribution into a local folder (e.g., ~/jboss-eap-8).  

Set the EAP_HOME environment variable as follows:

[source,sh,role="copypaste"]
----
export EAP_HOME=/shared/jboss-eap-8.0.0.Beta
----

Now we can move on to the migration from JBoss EAP 7.4 to JBoss EAP 8.0 Beta.

## Server configuration changes
When we deployed our application to JBoss EAP 7.4, we made some changes to the server configuration to add a module and driver to connect to MySQL. We must ensure these modules and drivers are in place and working correctly in our JBoss EAP 8-Beta server. We can use the JBoss EAP server migration tool to perform this migration for us.  

[source,sh,role="copypaste"]
----
cd /shared
----

[source,sh,role="copypaste"]
----
unzip jboss-eap-8.0.0.Beta-server-migration.zip
----

[source,sh,role="copypaste"]
----
cd jboss-eap-8.0.0.Beta-server-migration
----

Run the following command:

[source,sh,role="copypaste"]
----
./jboss-server-migration.sh -s $EAP_PREVIOUS_HOME -t $EAP_HOME
----

The server migration tool will ask a series of questions during the migration process:


----
----------------------------------------------------------

----  JBoss Server Migration Tool  -----------------------

----------------------------------------------------------


Retrieving servers...

 INFO  SOURCE server name: JBoss EAP, version: 7.4.0.GA.

 INFO  TARGET server name: JBoss EAP, version: 8.0.0.Beta.


----------------------------------------------------------

----------------------------------------------------------


Server migration starting...


 INFO  --- Migrating modules requested by environment...


 INFO  No modules to migrate.


Migrate the source's standalone server?

yes/no?


Choose yes to migrate the standalone configuration.

 INFO  --- Migrating standalone server...


 INFO  Source's standalone content migrated.


 INFO  Source's standalone configurations found: [standalone-full-ha.xml, standalone-full.xml, standalone-ha.xml, standalone-load-balancer.xml, standalone.xml]


Migrate all configurations?

yes/no? 
Choose no. We want to select the configurations to migrate.

Migrate configuration standalone-full-ha.xml ?

yes/no? 
Choose no. We don’t want to migrate standalone-full-ha.xml.

Migrate configuration standalone-full.xml ?

yes/no? 
Choose no. We don’t want to migrate standalone-full.xml

Migrate configuration standalone-ha.xml ?

yes/no? 
Choose no. We don’t want to migrate standalone-ha.xml.

Migrate configuration standalone-load-balancer.xml ?

yes/no? 
Choose no. We don’t want to migrate standalone-load-balancer.xml.

Migrate configuration standalone.xml ?

yes/no? 
Choose yes. We want to migrate standalone.xml.

 INFO  Migrating standalone configuration standalone.xml...

 WARN  Migration of legacy security domain jboss-web-policy's authorization is not supported and will be ignored.

 WARN  Migration of legacy security domain jaspitest's authentication-jaspi is not supported and will be ignored.

 WARN  Migration of legacy security domain jboss-ejb-policy's authorization is not supported and will be ignored.

 INFO  Legacy security XML configuration retrieved.

 INFO  Unsupported extensions removed: [org.jboss.as.security]

 INFO  Unsupported subsystems removed: [urn:jboss:domain:security:2.0]

 INFO  Referenced paths migrated.

 INFO  Legacy security realms removed from XML configuration.

WARNING: An illegal reflective access operation has occurred

WARNING: Illegal reflective access by org.wildfly.extension.elytron.SSLDefinitions (jar:file:/home/philip/Downloads/wildfly-ee-dist-8.0.0.Beta-redhat-00002/jboss-eap-8.0/modules/system/layers/base/org/wildfly/extension/elytron/main/wildfly-elytron-integration-jakarta-19.0.0.Beta16-redhat-00004.jar!/) to method com.sun.net.ssl.internal.ssl.Provider.isFIPS()

WARNING: Please consider reporting this to the maintainers of org.wildfly.extension.elytron.SSLDefinitions

WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations

WARNING: All illegal access operations will be denied in a future release

 INFO  Legacy security realm ManagementRealm migrated to Elytron.

 INFO  Legacy security realm ApplicationRealm migrated to Elytron.

 INFO  Legacy security domain other migrated to Elytron.


Migrate the source's managed domain?

yes/no?
Choose no. We are not using a managed domain.

Server migration done.


 INFO  

----------------------------------------------------------------------------------------------------------

 Task Summary

----------------------------------------------------------------------------------------------------------


 server .......................................................................................... SUCCESS

  standalone ..................................................................................... SUCCESS

   contents.standalone.migrate-content-dir ....................................................... SUCCESS

    contents.standalone.migrate-content(path=7d/975dfd92d3b7a35f48054ad2190bdf7ebbeb3b/content) .. SUCCESS

    contents.standalone.migrate-content(path=b5/fe70630a477a851f755cc04eb5cc3030bb02db/content) .. SUCCESS

    contents.standalone.migrate-content(path=92/2cdbb0d087989ad5e6ecbd3c0123a34def19b7/content) .. SUCCESS

    contents.standalone.migrate-content(path=14/99d19995fc5835cb1c07eed113447b4fb46c4e/content) .. SUCCESS

    contents.standalone.migrate-content(path=3d/25c8107fcc4cf82f234dcf6ad5b8e926e7ec18/content) .. SUCCESS

    contents.standalone.migrate-content(path=45/9834b7318bd81b320829432fdef5a77bf93a19/content) .. SUCCESS

    contents.standalone.migrate-content(path=38/c53e35a6ab9d8a40016a5429f7115ff94e3ce7/content) .. SUCCESS

   standalone-configurations ..................................................................... SUCCESS

    standalone-configuration(source=standalone.xml) .............................................. SUCCESS


----------------------------------------------------------------------------------------------------------

 Migration Result: SUCCESS

----------------------------------------------------------------------------------------------------------


Once this operation completes, we can start our JBoss EAP 8.0 server with the following command from the JBoss EAP installation folder:

[source,sh,role="copypaste"]
----
$EAP_HOME/bin/standalone.sh
----

When the server has started successfully, we can test our configuration with the following commands:

[source,sh,role="copypaste"]
----
./jboss-cli.sh --connect
----

[source,sh,role="copypaste"]
----
/subsystem=datasources:installed-drivers-list
----

The output should show the MySQL driver as follows: