= Traditional app deployment on JBoss 7.4
:experimental:
:imagesdir: images

JBoss EAP 8.0 will provide support for https://jakarta.ee/release/10/[Jakarta EE 10]. Jakarta EE 10 brings a huge change to Jakarta EE compared to the Jakarta EE 8 specifications supported by EAP 7. JBoss EAP 8 also introduces changes in the following areas:

* Removal of Picketbox: This has been deprecated since the release of JBoss EAP 6.4. Any legacy security configurations must be migrated to the Elytron security subsystem. EAP users who have already migrated to Elytron don't need to make any changes.
* Removal of PicketLink: This has been deprecated since the release of JBoss EAP 6.4. Leveraging RH SSO is recommended for the single sign-on functionality previously offered with PicketLink.
Support for OpenID Connect (OIDC) will now be provided by the elytron-oidc-client subsystem instead of the separate RH-SSO OIDC adapter.
* SAML support is provided by the RH-SSO SAML adapter (Picketlink SAML has been removed). In JBoss EAP 8.0 GA, support for SAML will be provided by a new RH-SSO SAML Galleon Feature Pack.
* Hibernate 6.x: Read the https://docs.jboss.org/hibernate/search/6.0/migration/html_single/[Hibernate Search article] for guidance on migrating from 5.11.x to 6.0.x.
* Removal of JDK 8: JDK 11 or JDK 17 is now required.
* Jolokia and Prometheus removed: Red Hat will no longer support these features. JBoss EAP server exposes metrics through the server metrics endpoint: <server address>:<management port>/metrics.
Apache Log4j version 1 APIs removed: If your applications do not package log4j.jar and Log4j configuration as part of the application, then you must update them.
* New maven plugin: The new eap-maven-plugin uses Galleon technology to build the server based on the layer configuration needed in your application. This results in a reduced size and memory footprint, plus a reduced attack surface. If the JAR impacted by a CVE is not present, EAP will not be vulnerable to the CVE. The JBoss EAP 8 OpenShift images don’t contain EAP runtime binaries like it used to in EAP 6 and EAP 7. This plugin also supports the execution of JBoss EAP CLI script files to customize your server configuration. OpenShift Source to Image builds (S2I) incorporate this change and have been redesigned to leverage the eap-maven-plugin to create the server. You can find more information in the https://access.redhat.com/documentation/en-us/red_hat_jboss_enterprise_application_platform/8.0-beta/[documentation].
* Bridge deploy fail: Previously, if a bridge were misconfigured, you wouldn’t know until you tried to use it. Now, the bridge will fail when added if it fails to deploy.

Refer to the https://access.redhat.com/documentation/en-us/red_hat_jboss_enterprise_application_platform/8-beta/html/release_notes_for_red_hat_jboss_enterprise_application_platform_8.0_beta/index[release notes] for more information about the changes introduced in this beta release.

Moving applications from JBoss EAP 7.4 to JBoss EAP 8.0 Beta will require code changes due to the move from Jakarta EE 8 to Jakarta EE 10 (e.g., converting from the “javax” namespace to “jakarta” namespace). These changes are documented in this https://access.redhat.com/articles/6980265[article]. To help our customers with this migration effort we've updated our tools: the https://developers.redhat.com/products/mta/download[Migration Toolkit for Applications], including the Migration Toolkit for Runtimes (MTR, for non-OpenShift projects) and the JBoss EAP Server Migration tool. 

In this section we're going to use the JBoss EAP Server Migration tool migrate the server configuration from JBoss EAP 7.4 to JBoss EAP 8-Beta

